<?php
/**
 * Created by PhpStorm.
 * User: JustThinkIt
 * Date: 2018/8/17
 * Time: 23:06
 */

namespace app\home\controller;
use think\Request;
use think\facade\Session;
// use app\common\model\Post;


class Post extends Common
{
    protected $pk = 'pid';
    protected $table = 'post';
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

    }

    /**
     * 帖子增加
     */
    public function add()
    {
        if(!is_login()){
            return $this->error('没有登录','home/user/login');
        }

        if ($this->request->method() == 'post')
        {
            halt($this->request->param());
        }
        $posts = $this->request->param('post');

        $this->assign('attach', time());
        $this->assign('title', '帖子发布');
        return $this->fetch();



    }

    /**
     * 帖子编辑
     */
    public function edit()
    {

    }

    /**
     * 帖子获取
     */
    public function detail($id=233)
    {
        // halt(Request::method());
        // if ()
        // halt(Session::get('user_name'));
        if(!is_login()){
            return $this->error('没有登录','home/user/login');
        }

        $data = db('post')->where('pid',$id)
            // ->field('create_time, update_time, title, content, username, reply_count, click_count')
            ->find();
        if (empty($data))  //没有此帖子内容,跳转到列表页
        {
            $this->error('没有此内容','home/index/index');
        }

        $reply = db('reply')->alias('r')->join('user u','u.uid=r.uid')
            ->where('r.pid',$id)
            ->field('u.username, r.uid, r.create_time, r.update_time, r.content')
            ->order('r.update_time desc')
            ->paginate(10);
        $page = $reply->render();
        $this->assign('post',$data);
        $this->assign('reply_list',$reply);
        $this->assign('page', $page);
        $this->assign('title','帖子列表');
        return $this->fetch();
    }

    /**
     * 帖子删除
     */
    public function delete()
    {

    }

    /**
     * 帖子隐藏
     */
    public function hide()
    {

    }
}